### ISSUE TITLE
Initial Push returns 

### ISSUE THREAD

**Issue by crsanghani** [makersacademy/clmystery#229]
I'm attempting to make my initial push and seem to be getting an error 403, anyone know why this might be?

`Username for 'https://github.com': crsanghani@gmail.com
Password for 'https://crsanghani@gmail.com@github.com':
remote: Permission to makersacademy/clmystery.git denied to crsanghani.
fatal: unable to access 'https://github.com/makersacademy/clmystery.git/': The requested URL returned error: 403`

**Comment by hanrattyjen** [comment]
Check your username. Your github username here is showing at crsanghani but from your paste, it's crsanghani@gmail.com. That might be why access is forbidden.

**Comment by hanrattyjen** [comment]
Check your username. Your github username above is crsanghani, but from your paste it is crsanghani@gmail.com.  Your can check your github username from typing this into the command line.

**Comment by crsanghani** [comment]
Nice catch but no dice : /

`Username for 'https://github.com': crsanghani
Password for 'https://crsanghani@github.com':
remote: Permission to makersacademy/clmystery.git denied to crsanghani.
fatal: unable to access 'https://github.com/makersacademy/clmystery.git/': The requested URL returned error: 403
`

**Comment by hanrattyjen** [comment]
Have you forked and cloned the clmystery from the Makers Academy repo? I may be wrong but it looks like you're trying to push it to the Makers Academy repo rather than your own.  I had a quick look at your profile and you have no public repos yet, whereas if you had forked the MA one, it would be showing.

**Comment by darrenf54321** [comment]
@hanrattyjen is correct I think. Have a look at the other students repos. We've all forked from Makers - I can't see anything in your repo profile either.

**Comment by crsanghani** [comment]
I did fork it, I was unsure as well, so I went and checked, I tried to a refork and got a message telling me that I already have a fork... 

The reason its not showing up I guess is because I have pushed to it...

**Comment by crsanghani** [comment]
Got it! 
Had to run this:
`
git remote set-url origin https://yourusername@github.com/user/repo.git
`
