### ISSUE TITLE
not passing the test after completing(?) the challenge

### ISSUE THREAD

**Issue by brzoskwinka18** [makersacademy/clmystery#289]
My suspects.txt contains 4 suspects, and all the information about them, and it doesn't pass the test. I also tried to make the pull request using a file suspects.txt with all the information but weight, and it still does not pass the test.

**Comment by brzoskwinka18** [comment]
do we pass the test only after adding the jail file?

**Comment by nikeshashar** [comment]
@brzoskwinka18 Please could you include a link to your code or your latest PR?

**Comment by brzoskwinka18** [comment]
https://github.com/makersacademy/clmystery/pull/291

**Comment by kwilson541** [comment]
Hi Agata - I had the same concerns initially and thought I'd messed up until I looked at the details. If you look at the job log for your pull request (and indeed many of the others with red crosses) you will see some red text regarding jail.txt - this file cannot be found because you haven't made it yet. Carry on with the challenge and check your pull request again after the last push!

**Comment by brzoskwinka18** [comment]
ok, so we're not meant to pass the test at this stage. got it. I went on and completed the challenge, or so I thought, and still not passing the test

**Comment by brzoskwinka18** [comment]
here is my latest pull request reference https://github.com/makersacademy/clmystery/pull/297/files

**Comment by nikeshashar** [comment]
https://travis-ci.org/makersacademy/clmystery/builds/167498888 is what I'm looking at @brzoskwinka18. 

There's an error message here : 

`The command "find ./ -name "jail.txt" | xargs less | $(command -v md5 || command -v md5sum) | grep -qif /dev/stdin encoded" exited with 1.`

**Comment by brzoskwinka18** [comment]
yes, if I understand correctly it doesn't find the file jail.txt 

which I created. and it's part of my PR

**Comment by bryonywatson1** [comment]
I have the exact same issue!

**Comment by brzoskwinka18** [comment]
As the person in the other github issue found out, in order to pass the test you need the name of the culprit and press enter afterwards
