### ISSUE TITLE
Not passing the CI tests after completing the challenge

### ISSUE THREAD

**Issue by simonconway1979** [makersacademy/clmystery#303]
Hi Guys,
Hope you're well. 

This is a continuation of the issues I posted on Slack. I thought I should add it as a git issue because I'm a bit stuck...

Here is my position. 

I found the killer. 
I tested this with the solutions file and I have the correct name. 
I checked the permissions of the file. I can read, write and execute, groups and others can read only. 
I have added the jail.txt file to git
I have committed the changes
I have pushed this to the makers git.

The CI test comes up with an error. 
The error is with this bit of code which is the test:

$ find ./ -name "jail.txt" | xargs less | $(command -v md5 || command -v md5sum) | grep -qif /dev/stdin encoded

This is basically very similar to the code in the solutions file that checks the name of the killer. 

So somewhere between pointing terminal to the correct name and pointing terminal on makers git to a file containing the correct name, I've messed something up. 

I reckon this will be something silly with my file that I haven't done or have missed. 
I've tried deleting it and making it again, making it with a text editorvinstead of command line, changing the permissions. 

Not quite sure what to do now. 
(No doubt I'll feel stupid when I find out what I did wrong.)

Any suggestions are welcome.

**Comment by brzoskwinka18** [comment]
I have the same problem.

**Comment by mikehurl** [comment]
Is it possible that is because you haven't deleted the Clues_from_Crime_Scene_Report file?

**Comment by anitacanita** [comment]
@brzoskwinka18 @simonconway1979 Did you make sure to type the name and not copy paste? Are you sure there aren't extra spaces? You might have a hidden whitespace character somewhere, sometimes it happens. If typing the name of the suspect and nothing else, doesn't solve it, don't worry, I see that you have completed the challenge :)

**Comment by brzoskwinka18** [comment]
Definitely no whitespace, if I cat jail.txt it prints everything in one line. Also definitely typed it. 

Jeremy BowersAgatas-MacBook-Air:clmystery Agata$

@mikehurl we're instructed to keep clues.txt so I did, and I think some of the people who passed the test also have it.

**Comment by keomony** [comment]
same problem here :( . I couldn't pass the same test code 
$ find ./ -name "jail.txt" | xargs less | $(command -v md5 || command -v md5sum) | grep -qif /dev/stdin encoded

**Comment by simonconway1979** [comment]
Awesome!!!!
After messing around for quite a while I found out that I needed a return after the name.

I checked some of the files that passed. They had 14 bytes. Mine had 13 bytes.
So I added a return and hey presto! It worked!!

Imagine... several hours of work just to add a return! (Welcome to coding : )

**Comment by anitacanita** [comment]
Great sleuthing @simonconway1979 :female_detective:

**Comment by bryonywatson1** [comment]
@simonconway1979  genius!
