### ISSUE TITLE
step6 having trouble grepping

### ISSUE THREAD

**Issue by bryonywatson1** [makersacademy/clmystery#310]
I am really struggling to figure out what the right code is to grep multiple pieces of text in the vehicles file. I have tried piping so 
grep -A 5 'L377' mystery/vehicles | grep -B 1 -A 4 'Honda' | grep -B 2 -A 3 'Blue' | grep -B 4 -A 1 'Height: 6' >> suspects.txt
 but nothing appears in suspects.txt 
I'm definitely missing something! Can anyone help?

**Comment by malinpatel** [comment]
I did grep L337 | grep -A 4 -B 1 Honda | grep -A 3 -B 2 Blue | grep -A 1 -B 4  'Height: 6'

**Comment by bryonywatson1** [comment]
@malinpatel thank you! Have just worked out where I was going wrong :-)
