### ISSUE TITLE
clmystery - Not sure if I'm finished

### ISSUE THREAD

**Issue by Putterhead** [makersacademy/clmystery#361]
Hey Everyone, Other than seeing that my pull request is green and I've added, committed and pushed the 'jail.txt' to clmystery, is there a rocksolid way of knowing I've completed the challenge?

**Comment by anitacanita** [comment]
@Putterhead Make sure to open any PreCourse related issue in https://github.com/makersacademy/pre_course/issues, this page isn't being monitored and it doesn't get posted in slack.

Anyway, I can confirm you have completed the challenge, well done! 👍
